application: nyt-delivery-companion
version: alpha-001
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: .*
  script: api.app

libraries:
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: MySQLdb
  version: "latest"
