runtime: python27
api_version: 1
threadsafe: yes
vm: true

handlers:
- url: .*
  script: api.app

libraries:
- name: MySQLdb
  version: "latest"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"

beta_settings:
  cloud_sql_instances: "nyt-delivery-companion:us-central1:nyt-delivery-companion-db2"
